export const DEFAULT_CATEGORIES = [
  { name: "Makanan", color: "red", icon: "CookieIcon" },
  { name: "Transportasi", color: "orange", icon: "Bus01Icon" },
  { name: "Belanja", color: "yellow", icon: "ShoppingCart01Icon" },
  { name: "Tagihan", color: "green", icon: "Invoice01Icon" },
  { name: "Hiburan", color: "purple", icon: "GameController01Icon" },
  { name: "Kesehatan", color: "pink", icon: "HealthIcon" },
  { name: "Pendidikan", color: "blue", icon: "SchoolIcon" },
  { name: "Rumah Tangga", color: "blue", icon: "Home01Icon" },
  { name: "Pakaian & Aksesoris", color: "purple", icon: "TShirtIcon" },
  { name: "Asuransi", color: "green", icon: "FavouriteIcon" },
  { name: "Tabungan & Investasi", color: "purple", icon: "Wallet01Icon" },
  { name: "Hadiah & Donasi", color: "pink", icon: "GiftIcon" },
  { name: "Perjalanan", color: "pink", icon: "Bus01Icon" },
  { name: "Penyesuaian", color: "gray", icon: "Audit01Icon" },
  { name: "Lainnya", color: "gray", icon: "More01Icon" },
  { name: "Gaji", color: "green", icon: "Wallet01Icon" },
  { name: "Bonus", color: "green", icon: "GiftIcon" },
  { name: "Freelance", color: "blue", icon: "Briefcase01Icon" },
  { name: "Investasi", color: "purple", icon: "Wallet01Icon" },
  { name: "Hadiah", color: "pink", icon: "GiftIcon" },
  { name: "Lainnya Pemasukan", color: "gray", icon: "More01Icon" },
] as const;
